'use client';

import { useCallback, useEffect, useMemo, useRef, useState } from "react";
import { useRouter, useSearchParams } from "next/navigation";
import Image from "next/image";
import { Info, Loader2, MapPin } from "lucide-react";

import { AppHeader } from "@/components/AppHeader";
import { MyCreationsSidebar } from "@/components/MyCreationsSidebar";
import { AspectRatioSelector } from "@/components/AspectRatioSelector";
import { AdditionalSettings } from "@/components/AdditionalSettings";
import { BottomNavigation } from "@/components/BottomNavigation";
import { useAppDispatch, useAppSelector } from "@/store/hooks";
import { setPrompt } from "@/features/prompt/promptSlice";
import { setGenerationResult } from "@/features/generation/generationSlice";

type ModelItem = {
  id: string;
  model: string;
  style: string;
  label: string;
  thumbnail: string;
};

type AspectRatio = '1:1' | '2:3' | '3:2' | '3:4' | '4:3';

export default function TextToImagePage() {
  const prompt = useAppSelector((state) => state.prompt.value);
  const dispatch = useAppDispatch();
  const searchParams = useSearchParams();
  const router = useRouter();
  const autoGenerateFlag = searchParams.get("auto") === "1";
  const hasAutoGeneratedRef = useRef(false);

  const [models, setModels] = useState<ModelItem[]>([]);
  const [modelsLoading, setModelsLoading] = useState(true);
  const [selectedModelId, setSelectedModelId] = useState<string>("");
  const [aspectRatio, setAspectRatio] = useState<AspectRatio>("1:1");
  const [generating, setGenerating] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [resultImage, setResultImage] = useState<string | null>(null);
  const [isMobile, setIsMobile] = useState(true);

  useEffect(() => {
    const updateDevice = () => {
      if (typeof window !== "undefined") {
        setIsMobile(window.innerWidth < 1024);
      }
    };
    updateDevice();
    window.addEventListener("resize", updateDevice);
    return () => window.removeEventListener("resize", updateDevice);
  }, []);

  useEffect(() => {
    const loadModels = async () => {
      setModelsLoading(true);
      try {
        const response = await fetch("/api/models");
        const json = await response.json();
        setModels(json.data);
        if (json.data.length > 0) {
          setSelectedModelId(json.data[0].id);
        }
      } catch (err) {
        setError("Failed to load models.");
        console.error(err);
      } finally {
        setModelsLoading(false);
      }
    };
    loadModels();
  }, []);

  const selectedModel = useMemo(
    () => models.find((item) => item.id === selectedModelId),
    [models, selectedModelId]
  );

  const handleGenerate = useCallback(async () => {
    if (!prompt.trim() || !selectedModel) return;
    setGenerating(true);
    setError(null);
    try {
      const response = await fetch("/api/generate", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ prompt, model: selectedModel.id, aspectRatio }),
      });
      const json = await response.json();
      if (!response.ok) {
        throw new Error(json.error ?? "Unable to generate image.");
      }
      setResultImage(json.imageUrl);
      dispatch(setGenerationResult({ imageUrl: json.imageUrl, prompt }));
      if (isMobile) {
        router.push("/result");
      }
    } catch (err) {
      console.error(err);
      setError("Generation failed. Please try again.");
    } finally {
      setGenerating(false);
    }
  }, [prompt, selectedModel, aspectRatio, dispatch, router, isMobile]);

  useEffect(() => {
    if (
      autoGenerateFlag &&
      !hasAutoGeneratedRef.current &&
      !modelsLoading &&
      selectedModel &&
      prompt.trim()
    ) {
      // Small delay to ensure UI is ready
      const timer = setTimeout(() => {
        hasAutoGeneratedRef.current = true;
        handleGenerate();
      }, 500);
      return () => clearTimeout(timer);
    }
  }, [autoGenerateFlag, modelsLoading, selectedModel, prompt, handleGenerate]);

  // Desktop placeholder
  const StarryNightPlaceholder = () => (
    <div className="relative h-full w-full overflow-hidden rounded-2xl bg-gradient-to-b from-slate-800 via-slate-900 to-slate-950">
      <div className="absolute inset-0">
        {Array.from({ length: 40 }).map((_, i) => (
          <div
            key={i}
            className="absolute rounded-full bg-white/80"
            style={{
              left: `${Math.random() * 100}%`,
              top: `${Math.random() * 100}%`,
              width: `${Math.random() * 3 + 1}px`,
              height: `${Math.random() * 3 + 1}px`,
              opacity: Math.random() * 0.8 + 0.2,
            }}
          />
        ))}
      </div>
      <div className="absolute bottom-0 left-0 right-0 h-32">
        <svg className="h-full w-full" viewBox="0 0 800 200" preserveAspectRatio="none">
          <path
            d="M0,200 L100,150 L200,180 L300,120 L400,160 L500,100 L600,140 L700,90 L800,130 L800,200 Z"
            fill="#1a1a2e"
          />
          <path
            d="M0,200 L150,140 L250,170 L350,110 L450,150 L550,90 L650,130 L750,80 L800,120 L800,200 Z"
            fill="#16213e"
            opacity="0.8"
          />
        </svg>
      </div>
    </div>
  );

  return (
    <div className="min-h-screen bg-gradient-to-br from-white via-slate-50 to-pink-50 px-4 py-6 text-slate-900 pb-24 md:px-8 md:py-8 md:pb-8">
      <div className="mx-auto flex max-w-7xl flex-col gap-6">
        <AppHeader />

        <div className="flex flex-1 gap-6">
          <MyCreationsSidebar />

          <main className="flex w-full flex-col gap-6 lg:flex-row lg:items-start lg:justify-center">
            {/* Desktop preview */}
            <section className="hidden flex-1 lg:flex lg:items-start lg:justify-center">
              <div className="flex h-[520px] w-full max-w-2xl items-center justify-center rounded-3xl border border-slate-200 bg-slate-50 shadow-xl">
                {resultImage ? (
                  <div className="relative h-full w-full">
                    <Image
                      src={resultImage}
                      alt="Generated artwork"
                      fill
                      sizes="(max-width: 1400px) 60vw, 600px"
                      className="rounded-3xl object-contain"
                    />
                  </div>
                ) : (
                  <StarryNightPlaceholder />
                )}
                {generating && (
                  <div className="absolute inset-0 flex items-center justify-center rounded-3xl bg-black/40 text-white">
                    <div className="flex items-center gap-3">
                      <Loader2 className="h-5 w-5 animate-spin" />
                      <span>Generating...</span>
                    </div>
                  </div>
                )}
              </div>
            </section>

            <section className="flex w-full flex-col gap-6 lg:w-[420px]">
              {/* Prompt Input */}
              <div className="space-y-2">
                <label className="text-sm font-semibold text-slate-700">
                  Describe what you want to create
                </label>
                <div className="relative rounded-2xl border border-pink-200 bg-white shadow-sm">
                  <textarea
                    value={prompt}
                    onChange={(event) => dispatch(setPrompt(event.target.value))}
                    rows={4}
                    className="w-full rounded-2xl border-none bg-transparent p-4 pr-10 text-sm text-slate-800 outline-none"
                    placeholder="Describe what you want to create"
                  />
                  <MapPin className="absolute bottom-3 right-3 h-4 w-4 text-pink-500" />
                </div>
              </div>

              {/* Additional Settings */}
              <div className="flex justify-center">
                <AdditionalSettings>
                  <div className="space-y-2 text-xs text-slate-600">
                    <p>Advanced generation parameters will appear here</p>
                  </div>
                </AdditionalSettings>
              </div>

              {/* Aspect Ratio */}
              <div className="space-y-3">
                <div className="flex items-center gap-2 text-sm font-semibold text-slate-700">
                  <span>Aspect Ratio</span>
                  <Info className="h-4 w-4 text-slate-400" />
                </div>
                <AspectRatioSelector value={aspectRatio} onChange={setAspectRatio} />
              </div>

              {/* Models & Styles */}
              <div className="space-y-3">
                <div className="flex items-center gap-2 text-sm font-semibold text-slate-700">
                  <span>Models & Styles</span>
                  <Info className="h-4 w-4 text-slate-400" />
                </div>

                {selectedModel && (
                  <div className="grid grid-cols-2 gap-3 rounded-2xl bg-white/70 p-3 shadow-sm">
                    <div className="flex items-center gap-2 rounded-2xl border-2 border-orange-400/60 bg-orange-50/70 px-3 py-2">
                      <div className="relative h-10 w-10 overflow-hidden rounded-full border border-white">
                        {selectedModel.thumbnail ? (
                          <Image
                            src={selectedModel.thumbnail}
                            alt={selectedModel.label}
                            fill
                            sizes="40px"
                            className="object-cover"
                          />
                        ) : (
                          <div className="flex h-full w-full items-center justify-center bg-slate-200 text-xs text-slate-500">
                            Img
                          </div>
                        )}
                      </div>
                      <div className="text-left">
                        <p className="text-[10px] uppercase tracking-wide text-orange-500">
                          Model
                        </p>
                        <p className="text-sm font-semibold text-slate-900 line-clamp-1">
                          {selectedModel.model}
                        </p>
                      </div>
                    </div>
                    <div className="flex items-center gap-2 rounded-2xl border-2 border-pink-400/60 bg-pink-50/70 px-3 py-2">
                      <div className="relative h-10 w-10 overflow-hidden rounded-full border border-white">
                        {selectedModel.thumbnail ? (
                          <Image
                            src={selectedModel.thumbnail}
                            alt={selectedModel.style}
                            fill
                            sizes="40px"
                            className="object-cover"
                          />
                        ) : (
                          <div className="flex h-full w-full items-center justify-center bg-slate-200 text-xs text-slate-500">
                            Img
                          </div>
                        )}
                      </div>
                      <div className="text-left">
                        <p className="text-[10px] uppercase tracking-wide text-pink-500">
                          Style
                        </p>
                        <p className="text-sm font-semibold text-slate-900 line-clamp-1">
                          {selectedModel.style ?? "Custom"}
                        </p>
                      </div>
                    </div>
                  </div>
                )}

                {/* Models Grid */}
                <div className="grid grid-cols-3 gap-2">
                  {modelsLoading &&
                    Array.from({ length: 9 }).map((_, index) => (
                      <div
                        key={index}
                        className="aspect-square animate-pulse rounded-xl bg-slate-100"
                      />
                    ))}
                  {!modelsLoading &&
                    models.slice(0, 9).map((model) => (
                      <button
                        key={model.id}
                        type="button"
                        onClick={() => setSelectedModelId(model.id)}
                        className={`overflow-hidden rounded-xl border text-left transition ${
                          selectedModelId === model.id
                            ? "border-orange-400 ring-2 ring-orange-200"
                            : "border-slate-200 hover:border-slate-300"
                        }`}
                      >
                        <div className="relative aspect-square w-full">
                          {model.thumbnail ? (
                            <Image
                              src={model.thumbnail}
                              alt={model.label}
                              fill
                              sizes="(max-width: 1024px) 33vw, 120px"
                              className="object-cover"
                            />
                          ) : (
                            <div className="flex h-full items-center justify-center bg-slate-100 text-xs text-slate-400">
                              Preview
                            </div>
                          )}
                        </div>
                        <div className="px-2 py-1.5">
                          <p className="text-xs font-medium text-slate-700 truncate">
                            {model.label}
                          </p>
                        </div>
                      </button>
                    ))}
                </div>
              </div>

              {error && (
                <p className="rounded-xl bg-red-50 px-4 py-3 text-sm text-red-600">
                  {error}
                </p>
              )}

            {/* Generate Button */}
            <button
              type="button"
              onClick={handleGenerate}
              disabled={generating || !prompt.trim() || !selectedModel}
              className="rounded-2xl bg-gradient-to-r from-orange-500 to-pink-500 px-6 py-4 text-base font-semibold text-white shadow-lg transition hover:opacity-90 disabled:cursor-not-allowed disabled:bg-slate-300 disabled:text-slate-500"
            >
              {generating ? "Generating..." : "Generate"}
            </button>
          </section>

          </main>
        </div>
      </div>
      <BottomNavigation />
    </div>
  );
}
